### ISSUE TITLE
Error while running with react-native 0.56

### ISSUE THREAD

**Issue by shashanksinghal** [douglasjunior/react-native-simple-dialogs#13]
When running app with react-native 0.56, I get following error:

> undefined is not an object (evaluating '_reactNative.ActivityIndicator.propTypes.color')

at ProgressDialog.js 56:56

**Comment by douglasjunior** [comment]
Thanks for reporting.

**Comment by EdwinJDiaz** [comment]
thank you @douglasjunior

**Comment by shashanksinghal** [comment]
Thanks @douglasjunior for the library.

I just wanted to know if any updates on this as I tested other plugins with 0.5.6 and only this is left to upgrade now.

No rush or push, I am just asking so as otherwise I will fork and try to create a PR.

Thanks

**Comment by douglasjunior** [comment]
Hi @shashanksinghal, sorry, I did not have time to fix. A PR will be welcome 😃

**Comment by bhavincitrusbug** [comment]
i have same issue

**Comment by akriger** [comment]
@douglasjunior @shashanksinghal @hjbaek @bhavincitrusbug 

This can be fixed with the changes below if someone wants to create a PR.

in ProgressDialog.js change lines 56 - 58 to the below

`
activityIndicatorColor: PropTypes.string,
activityIndicatorSize: PropTypes.string,
activityIndicatorStyle: PropTypes.style
`

**Comment by hugohow** [comment]
I've created one : https://github.com/douglasjunior/react-native-simple-dialogs/pull/14

**Comment by douglasjunior** [comment]
Fixed by #14
