### ISSUE TITLE
How to change position of Dialog

### ISSUE THREAD

**Issue by Benzer1406** [douglasjunior/react-native-simple-dialogs#35]
I would like to change the position of the ConfirmDialog. As soon as a TextInput in the ConfirmDialog gets the focus I would like to scroll it up a little bit since it's overlapping with the keyboard. How can I do that?

**Comment by douglasjunior** [comment]
On Android you can just add `android:windowSoftInputMode="adjustResize"` to your activity. And for iOS you can use the https://github.com/douglasjunior/react-native-keyboard-manager.

**Comment by pratikghosalkar** [comment]
one hack is, you can add a negative top margin to dialog style so that it will always stay above the keyboard.
```
dialogStyle={{
alignSelf: 'center',
marginTop: -150 // adjust according to your need
}}
```

NOTE - It's not a proper way, its just a hack. In my case, [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview) was also not working properly so I have added top margin it like this.

**Comment by douglasjunior** [comment]
@pratikghosalkar try to add the same value to `marginBottom` in the `overlayStyle`.
